#!/usr/bin/env bash
name="lxde-base"
version="1.0.0"
description="lxde package list "
source=""
depends="libfm,libfm-extra,menu-cache,lxappearance,lxde-common,lxde-icon-theme,lxhotkey,lxinput,lxlauncher,lxmenu-data,lxpanel,lxrandr,lxsession,lxtask,lxterminal,pcmanfm"
group="lxde.base"

setup(){
	echo ""
}

build(){
   echo ""
}

package(){
mkdir -p $DESTDIR/tmp/
touch $DESTDIR/tmp/lxde-base
 
}

